#!/usr/bin/env python
#=========================================================================
# regincr-sim <input-pattern>
#=========================================================================

import os
import sys
import random

from pymtl3 import *
from pymtl3.passes.backends.verilog import *

# Hack to add project root to python path

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + ".pymtl_sim_root" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

from regincr.RegIncrNstageRTL import RegIncrNstageRTL

# Choose input pattern

pattern = sys.argv[1]

input_values = []
if pattern == "random":
  input_values = [ random.randint(0,255) for _ in range(0,100) ]
elif pattern == "zeros":
  input_values = [ 0 for _ in range(0,100) ]

# Add some zero values to end of list of input values

input_values.extend( [0]*5 )

# Instantiate a 4-stage registered incrementer

model = RegIncrNstageRTL( nstages=4 )
model.elaborate()

# Mark the top-level component for translation

model.set_metadata( VerilogTranslationImportPass.enable, True )

# Apply the pass groups

model.apply( VerilogPlaceholderPass() )
model = VerilogTranslationImportPass()( model )

model.set_metadata( VerilogTBGenPass.case_name, pattern )
model.apply( VerilogTBGenPass() )
model.apply( DefaultPassGroup(linetrace=True) )

# Reset simulator

model.sim_reset()

# Apply input values and display output values

for input_value in input_values:

  # Write input value to input port

  model.in_ @= input_value

  # Evaluate combinational logic

  model.sim_eval_combinational()

  # Tick simulator one cycle

  model.sim_tick()

